openapi: 3.0.0
info:
  title: SwingNotes API
  version: 1.0.0
  description: SwingNotes API

servers:
  - url: http://localhost:4000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

tags:
  - name: Auth
    description: Authentication routes
  - name: Notes
    description: Note management

paths:
  /api/v1/auth/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, name]
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        201:
          description: User registered
        400:
          description: Validation error

  /api/v1/auth/login:
    post:
      tags: [Auth]
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
        401:
          description: Invalid credentials

  /api/v1/auth/me:
    get:
      tags: [Auth]
      summary: Get current user
      security:
        - bearerAuth: []
      responses:
        200:
          description: Returns current user
        401:
          description: Unauthorized

  /api/v1/notes:
    get:
      tags: [Notes]
      summary: Get all notes
      responses:
        200:
          description: List of notes

    post:
      tags: [Notes]
      summary: Create a new note
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, content]
              properties:
                title:
                  type: string
                content:
                  type: string
                color:
                  type: string
      responses:
        201:
          description: Note created
        401:
          description: Unauthorized

  /api/v1/notes/{id}:
    get:
      tags: [Notes]
      summary: Get a note by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Note found
        404:
          description: Note not found

    put:
      tags: [Notes]
      summary: Update a note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                color:
                  type: string
      responses:
        200:
          description: Note updated
        404:
          description: Note not found

    delete:
      tags: [Notes]
      summary: Delete a note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Note deleted
        404:
          description: Note not found
